package io.keepagent.app.runtime

import android.content.Context
import com.android.tools.r8.D8
import com.android.tools.r8.D8Command
import com.android.tools.r8.OutputMode
import dalvik.system.DexClassLoader
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.PrintStream
import java.io.PrintWriter

/** Compiles ordinary Java source to dex and invokes its main method entirely on Android. */
class JavaRuntime(private val context: Context) {
    private val lock = Any()

    data class Result(val ok: Boolean, val text: String)

    fun run(root: File, relative: String, requestedMain: String?, args: List<String>): Result = synchronized(lock) {
        val workspace = root.canonicalFile
        val target = File(workspace, relative.ifBlank { "." }).canonicalFile
        require(target == workspace || target.path.startsWith(workspace.path + File.separator)) { "path escapes the active workspace" }
        require(target.exists()) { "path does not exist: $relative" }
        val sources = (if (target.isFile) sequenceOf(target) else target.walkTopDown())
            .filter { it.isFile && it.extension.equals("java", true) }
            .take(201).toList()
        require(sources.isNotEmpty()) { "no .java files found" }
        require(sources.size <= 200) { "Java run is limited to 200 source files" }
        require(sources.sumOf { it.length() } <= 2_000_000) { "Java sources are larger than 2 MB" }

        val mainClass = requestedMain?.takeIf { it.isNotBlank() } ?: inferMainClass(sources)
            ?: return Result(false, "Could not find a static main method. Choose a main class explicitly.")
        val build = File(context.codeCacheDir, "java-run/${System.nanoTime()}")
        val classes = File(build, "classes").apply { mkdirs() }
        val dex = File(build, "dex").apply { mkdirs() }
        try {
            val platformDir = File(context.codeCacheDir, "java-platform").apply { mkdirs() }
            val platformJars = listOf("core-for-system-modules.jar", "android.jar").map { name ->
                File(platformDir, name).also { output ->
                    if (!output.isFile) context.assets.open("java-platform/$name").use { input -> output.outputStream().use(input::copyTo) }
                }
            }
            // Android SDK stubs are a classic boot class path, not a desktop JDK
            // module image. Java 8 source mode is the interoperable on-device path.
            val compilerArgs = mutableListOf("-proc:none", "-bootclasspath", platformJars.joinToString(File.pathSeparator),
                "-encoding", "UTF-8", "-source", "8", "-target", "8", "-d", classes.path)
            compilerArgs += sources.map { it.path }
            val compilerOutput = ByteArrayOutputStream()
            val compileExit = PrintWriter(compilerOutput, true).use { out ->
                com.sun.tools.javac.Main.compile(compilerArgs.toTypedArray(), out)
            }
            if (compileExit != 0) return Result(false, compilerOutput.toString(Charsets.UTF_8.name()).ifBlank { "Java compilation failed" })

            val classFiles = classes.walkTopDown().filter { it.isFile && it.extension == "class" }.map { it.toPath() }.toList()
            D8.run(D8Command.builder().addProgramFiles(classFiles).setMinApiLevel(26).setOutput(dex.toPath(), OutputMode.DexIndexed).build())
            val dexFile = File(dex, "classes.dex")
            require(dexFile.setReadOnly()) { "Could not secure generated bytecode" }
            val loader = DexClassLoader(dexFile.path, File(build, "optimized").apply { mkdirs() }.path, null, context.classLoader)
            val stdout = ByteArrayOutputStream()
            val previousOut = System.out
            val previousErr = System.err
            try {
                PrintStream(stdout, true, Charsets.UTF_8.name()).use { captured ->
                    System.setOut(captured); System.setErr(captured)
                    val method = loader.loadClass(mainClass).getMethod("main", Array<String>::class.java)
                    method.invoke(null, args.toTypedArray() as Any)
                }
            } finally {
                System.setOut(previousOut); System.setErr(previousErr)
            }
            Result(true, stdout.toString(Charsets.UTF_8.name()).take(256_000).ifBlank { "Java program completed successfully." })
        } catch (e: Throwable) {
            val cause = (e.cause ?: e)
            Result(false, "${cause.javaClass.simpleName}: ${cause.message ?: "Java execution failed"}")
        } finally {
            build.deleteRecursively()
        }
    }

    private fun inferMainClass(sources: List<File>): String? {
        val mainPattern = Regex("static\\s+void\\s+main\\s*\\(")
        val packagePattern = Regex("(?m)^\\s*package\\s+([A-Za-z_][\\w.]*)\\s*;")
        val classPattern = Regex("(?:public\\s+)?(?:final\\s+)?class\\s+([A-Za-z_$][\\w$]*)")
        for (file in sources) {
            val text = file.readText().take(1_000_000)
            if (!mainPattern.containsMatchIn(text)) continue
            val name = classPattern.find(text)?.groupValues?.get(1) ?: file.nameWithoutExtension
            val pkg = packagePattern.find(text)?.groupValues?.get(1)
            return if (pkg == null) name else "$pkg.$name"
        }
        return null
    }
}
